name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: install libgbm1
        run: sudo apt-get install -y libgbm1

      - name: Intall deps
        run: |
          npm i

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test -- --watch=false

      - name: Build
        run: npm run build:prod

