name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: install libgbm1
        run: sudo apt-get install -y libgbm1

      - name: Intall deps
        run: |
          yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --watch=false

      - name: Build
        run: yarn build:prod

